CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE __yuniqldbversion (
    id smallint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    version character varying(32) NOT NULL,
    dateinsertedutc timestamp without time zone NOT NULL,
    lastupdatedutc timestamp without time zone NOT NULL,
    lastuserid character varying(128) NOT NULL,
    artifact bytea NULL,
    CONSTRAINT "PK___yuniqldbversion" PRIMARY KEY (id)
);

CREATE TABLE jobs (
    job_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    job_title character varying(35) NOT NULL,
    min_salary numeric(8,2) NULL,
    max_salary numeric(8,2) NULL,
    CONSTRAINT jobs_pkey PRIMARY KEY (job_id)
);

CREATE TABLE regions (
    region_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    region_name character varying(25) NULL,
    CONSTRAINT regions_pkey PRIMARY KEY (region_id)
);

CREATE TABLE "TestClass" (
    "TestId" text NULL,
    "TestColumn" text NULL
);

CREATE TABLE countries (
    country_id character(2) NOT NULL,
    country_name character varying(40) NULL,
    region_id integer NOT NULL,
    CONSTRAINT countries_pkey PRIMARY KEY (country_id),
    CONSTRAINT countries_region_id_fkey FOREIGN KEY (region_id) REFERENCES regions (region_id) ON DELETE CASCADE
);

CREATE TABLE locations (
    location_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    street_address character varying(40) NULL,
    postal_code character varying(12) NULL,
    city character varying(30) NOT NULL,
    state_province character varying(25) NULL,
    country_id character(2) NOT NULL,
    CONSTRAINT locations_pkey PRIMARY KEY (location_id),
    CONSTRAINT locations_country_id_fkey FOREIGN KEY (country_id) REFERENCES countries (country_id) ON DELETE CASCADE
);

CREATE TABLE departments (
    department_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    department_name character varying(30) NOT NULL,
    location_id integer NULL,
    CONSTRAINT departments_pkey PRIMARY KEY (department_id),
    CONSTRAINT departments_location_id_fkey FOREIGN KEY (location_id) REFERENCES locations (location_id) ON DELETE CASCADE
);

CREATE TABLE employees (
    employee_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    first_name character varying(20) NULL,
    last_name character varying(25) NOT NULL,
    email character varying(100) NOT NULL,
    phone_number character varying(20) NULL,
    hire_date date NOT NULL,
    job_id integer NOT NULL,
    salary numeric(8,2) NOT NULL,
    manager_id integer NULL,
    department_id integer NULL,
    CONSTRAINT employees_pkey PRIMARY KEY (employee_id),
    CONSTRAINT employees_department_id_fkey FOREIGN KEY (department_id) REFERENCES departments (department_id) ON DELETE CASCADE,
    CONSTRAINT employees_job_id_fkey FOREIGN KEY (job_id) REFERENCES jobs (job_id) ON DELETE CASCADE,
    CONSTRAINT employees_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES employees (employee_id) ON DELETE CASCADE
);

CREATE TABLE dependents (
    dependent_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    relationship character varying(25) NOT NULL,
    employee_id integer NOT NULL,
    CONSTRAINT dependents_pkey PRIMARY KEY (dependent_id),
    CONSTRAINT dependents_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES employees (employee_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX ix___yuniqldbversion ON __yuniqldbversion (version);

CREATE INDEX "IX_countries_region_id" ON countries (region_id);

CREATE INDEX "IX_departments_location_id" ON departments (location_id);

CREATE INDEX "IX_dependents_employee_id" ON dependents (employee_id);

CREATE INDEX "IX_employees_department_id" ON employees (department_id);

CREATE INDEX "IX_employees_job_id" ON employees (job_id);

CREATE INDEX "IX_employees_manager_id" ON employees (manager_id);

CREATE INDEX "IX_locations_country_id" ON locations (country_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200204174607_InitialCreate', '3.1.1');

