DROP TABLE IF EXISTS dbo.__yuniql_schema_version;

DROP TABLE IF EXISTS dbo.dependents;
DROP TABLE IF EXISTS dbo.employees;
DROP TABLE IF EXISTS dbo.departments;
DROP TABLE IF EXISTS dbo.jobs;
DROP TABLE IF EXISTS dbo.locations;
DROP TABLE IF EXISTS dbo.countries;
DROP TABLE IF EXISTS dbo.regions;

DROP TABLE IF EXISTS dbo.my_versions;

IF EXISTS(SELECT 1 FROM [sys].[schemas] WHERE name = 'my_schema')
BEGIN
	DROP TABLE IF EXISTS my_schema.__yuniql_schema_version;
	DROP TABLE IF EXISTS my_schema.my_versions;
	DROP SCHEMA IF EXISTS my_schema;
END

DROP TABLE IF EXISTS dbo.TEST_DB_OBJECT_1;
DROP TABLE IF EXISTS dbo.TEST_DB_OBJECT_2;
DROP TABLE IF EXISTS dbo.TEST_DB_OBJECT_3;
DROP TABLE IF EXISTS dbo.TEST_DB_OBJECT_4;
DROP TABLE IF EXISTS dbo.TEST_DB_OBJECT_5;
DROP TABLE IF EXISTS dbo.TEST_DB_OBJECT_6;
DROP TABLE IF EXISTS dbo.TEST_DB_OBJECT_7;
DROP TABLE IF EXISTS dbo.TEST_DB_OBJECT_8;
DROP TABLE IF EXISTS dbo.TEST_DB_OBJECT_9;
DROP TABLE IF EXISTS dbo.TEST_DB_OBJECT_10;
DROP TABLE IF EXISTS dbo.TEST_DB_OBJECT_11;
DROP TABLE IF EXISTS dbo.TEST_DB_OBJECT_12;
DROP TABLE IF EXISTS dbo.TEST_DB_OBJECT_13;
DROP TABLE IF EXISTS dbo.TEST_DB_OBJECT_14;
DROP TABLE IF EXISTS dbo.TEST_DB_OBJECT_15;
DROP TABLE IF EXISTS dbo.TEST_DB_OBJECT_16;
DROP TABLE IF EXISTS dbo.TEST_DB_OBJECT_1_Token1Value_Token2Value_Token3Value;

DROP TABLE IF EXISTS dbo.TestCsv;
DROP TABLE IF EXISTS dbo.TestCsvMismatchColumn;
DROP TABLE IF EXISTS dbo.TestCsvMismatchColumnNotNullable;
DROP TABLE IF EXISTS dbo.TestCsvNullColumn;
DROP TABLE IF EXISTS dbo.TestCsvNullWordValue;
DROP TABLE IF EXISTS dbo.TestCsvPipeSeparated;
DROP TABLE IF EXISTS dbo.TestCsvUnquoted;
DROP TABLE IF EXISTS dbo.TestCsvUtf8;

IF EXISTS(SELECT 1 FROM [sys].[schemas] WHERE name = 'TestSchema')
BEGIN
	DROP TABLE IF EXISTS TestSchema.TestCsv;
	DROP SCHEMA IF EXISTS TestSchema;
END
