DROP TABLE IF EXISTS PUBLIC.__YUNIQL_SCHEMA_VERSION;
GO

DROP TABLE IF EXISTS PUBLIC.DEPENDENTS;
GO
DROP TABLE IF EXISTS PUBLIC.EMPLOYEES;
GO
DROP TABLE IF EXISTS PUBLIC.DEPARTMENTS;
GO
DROP TABLE IF EXISTS PUBLIC.JOBS;
GO
DROP TABLE IF EXISTS PUBLIC.LOCATIONS;
GO
DROP TABLE IF EXISTS PUBLIC.COUNTRIES;
GO
DROP TABLE IF EXISTS PUBLIC.REGIONS;
GO

DROP TABLE IF EXISTS PUBLIC."my_versions";
GO
--DROP TABLE IF EXISTS "my_schema"."__yuniql_schema_version";
--GO
--DROP TABLE IF EXISTS "my_schema"."my_versions";
--GO
DROP SCHEMA IF EXISTS "my_schema" CASCADE;
GO

DROP TABLE IF EXISTS PUBLIC.TEST_DB_OBJECT_1;
GO
DROP TABLE IF EXISTS PUBLIC.TEST_DB_OBJECT_2;
GO
DROP TABLE IF EXISTS PUBLIC.TEST_DB_OBJECT_3;
GO
DROP TABLE IF EXISTS PUBLIC.TEST_DB_OBJECT_4;
GO
DROP TABLE IF EXISTS PUBLIC.TEST_DB_OBJECT_5;
GO
DROP TABLE IF EXISTS PUBLIC.TEST_DB_OBJECT_6;
GO
DROP TABLE IF EXISTS PUBLIC.TEST_DB_OBJECT_7;
GO
DROP TABLE IF EXISTS PUBLIC.TEST_DB_OBJECT_8;
GO
DROP TABLE IF EXISTS PUBLIC.TEST_DB_OBJECT_9;
GO
DROP TABLE IF EXISTS PUBLIC.TEST_DB_OBJECT_10;
GO
DROP TABLE IF EXISTS PUBLIC.TEST_DB_OBJECT_11;
GO
DROP TABLE IF EXISTS PUBLIC.TEST_DB_OBJECT_12;
GO
DROP TABLE IF EXISTS PUBLIC.TEST_DB_OBJECT_13;
GO
DROP TABLE IF EXISTS PUBLIC.TEST_DB_OBJECT_14;
GO
DROP TABLE IF EXISTS PUBLIC.TEST_DB_OBJECT_15;
GO
DROP TABLE IF EXISTS PUBLIC.TEST_DB_OBJECT_16;
GO

DROP TABLE IF EXISTS PUBLIC."TEST_DB_OBJECT_1_Token1Value_Token2Value_Token3Value";
GO

DROP TABLE IF EXISTS PUBLIC."TestCsv";
GO
DROP TABLE IF EXISTS PUBLIC."TestCsvMismatchColumn";
GO
DROP TABLE IF EXISTS PUBLIC."TestCsvMismatchColumnNotNullable";
GO
DROP TABLE IF EXISTS PUBLIC."TestCsvNullColumn";
GO
DROP TABLE IF EXISTS PUBLIC."TestCsvNullWordValue";
GO
DROP TABLE IF EXISTS PUBLIC."TestCsvPipeSeparated";
GO
DROP TABLE IF EXISTS PUBLIC."TestCsvUnquoted";
GO
DROP TABLE IF EXISTS PUBLIC."TestCsvUtf8";
GO

--DROP TABLE IF EXISTS "TestSchema"."TestCsv";
--GO
DROP SCHEMA IF EXISTS "TestSchema" CASCADE;
GO
