FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build-env

WORKDIR /code
COPY ./src .
RUN dotnet publish -c release -r win-x64 /p:publishtrimmed=true -o ./app

#https://github.com/dotnet/dotnet-docker/issues/1332
FROM mcr.microsoft.com/dotnet/core/aspnet:3.0 AS runtime-env

WORKDIR app
COPY --from=build-env /code/app .

ENTRYPOINT ["dotnet", "yuniql.dll", "run", "-p", "db"]
CMD ["additional-arguments-captured-from-docker-run"]