FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build-env

WORKDIR /code

# copy all files and directories from root src folder
COPY . .

WORKDIR /code/yuniql-cli
RUN dotnet publish -c release -r win-x64 /p:publishtrimmed=true -o ./app

FROM mcr.microsoft.com/dotnet/core/aspnet:3.0 AS runtime-env

WORKDIR app
COPY --from=build-env /code/yuniql-cli/app .

ENTRYPOINT ["dotnet", "yuniql.dll", "run", "-p", "db"]
CMD ["additional-arguments-captured-from-docker-run"]
