DROP TABLE IF EXISTS __yuniql_schema_version;

DROP TABLE IF EXISTS dependents;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS departments;
DROP TABLE IF EXISTS jobs;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS countries;
DROP TABLE IF EXISTS regions;

DROP TABLE IF EXISTS my_versions;

DROP TABLE IF EXISTS TEST_DB_OBJECT_1;
DROP TABLE IF EXISTS TEST_DB_OBJECT_2;
DROP TABLE IF EXISTS TEST_DB_OBJECT_3;
DROP TABLE IF EXISTS TEST_DB_OBJECT_4;
DROP TABLE IF EXISTS TEST_DB_OBJECT_5;
DROP TABLE IF EXISTS TEST_DB_OBJECT_6;
DROP TABLE IF EXISTS TEST_DB_OBJECT_7;
DROP TABLE IF EXISTS TEST_DB_OBJECT_8;
DROP TABLE IF EXISTS TEST_DB_OBJECT_9;
DROP TABLE IF EXISTS TEST_DB_OBJECT_10;
DROP TABLE IF EXISTS TEST_DB_OBJECT_11;
DROP TABLE IF EXISTS TEST_DB_OBJECT_12;
DROP TABLE IF EXISTS TEST_DB_OBJECT_13;
DROP TABLE IF EXISTS TEST_DB_OBJECT_14;
DROP TABLE IF EXISTS TEST_DB_OBJECT_15;
DROP TABLE IF EXISTS TEST_DB_OBJECT_16;

DROP TABLE IF EXISTS TEST_DB_OBJECT_1_Token1Value_Token2Value_Token3Value;
DROP PROCEDURE IF EXISTS TEST_DB_OBJECT_1_Token1Value_Token2Value_Token3Value;

DROP TABLE IF EXISTS TestCsv;
DROP TABLE IF EXISTS TestCsvMismatchColumn;
DROP TABLE IF EXISTS TestCsvMismatchColumnNotNullable;
DROP TABLE IF EXISTS TestCsvNullColumn;
DROP TABLE IF EXISTS TestCsvNullWordValue;
DROP TABLE IF EXISTS TestCsvPipeSeparated;
DROP TABLE IF EXISTS TestCsvUnquoted;
DROP TABLE IF EXISTS TestCsvUtf8;
