DROP TABLE IF EXISTS public.__yuniql_schema_version;

DROP TABLE IF EXISTS public.dependents;
DROP TABLE IF EXISTS public.employees;
DROP TABLE IF EXISTS public.departments;
DROP TABLE IF EXISTS public.jobs;
DROP TABLE IF EXISTS public.locations;
DROP TABLE IF EXISTS public.countries;
DROP TABLE IF EXISTS public.regions;

DROP TABLE IF EXISTS public.my_versions;
DROP SCHEMA IF EXISTS my_schema CASCADE;

DROP TABLE IF EXISTS public."TEST_DB_OBJECT_1";
DROP TABLE IF EXISTS public."TEST_DB_OBJECT_2";
DROP TABLE IF EXISTS public."TEST_DB_OBJECT_3";
DROP TABLE IF EXISTS public."TEST_DB_OBJECT_4";
DROP TABLE IF EXISTS public."TEST_DB_OBJECT_5";
DROP TABLE IF EXISTS public."TEST_DB_OBJECT_6";
DROP TABLE IF EXISTS public."TEST_DB_OBJECT_7";
DROP TABLE IF EXISTS public."TEST_DB_OBJECT_8";
DROP TABLE IF EXISTS public."TEST_DB_OBJECT_9";
DROP TABLE IF EXISTS public."TEST_DB_OBJECT_10";
DROP TABLE IF EXISTS public."TEST_DB_OBJECT_11";
DROP TABLE IF EXISTS public."TEST_DB_OBJECT_12";
DROP TABLE IF EXISTS public."TEST_DB_OBJECT_13";
DROP TABLE IF EXISTS public."TEST_DB_OBJECT_14";
DROP TABLE IF EXISTS public."TEST_DB_OBJECT_15";
DROP TABLE IF EXISTS public."TEST_DB_OBJECT_16";
DROP TABLE IF EXISTS public."TEST_DB_OBJECT_1_Token1Value_Token2Value_Token3Value";

DROP TABLE IF EXISTS public."TestCsv";
DROP TABLE IF EXISTS public."TestCsvMismatchColumn";
DROP TABLE IF EXISTS public."TestCsvMismatchColumnNotNullable";
DROP TABLE IF EXISTS public."TestCsvNullColumn";
DROP TABLE IF EXISTS public."TestCsvNullWordValue";
DROP TABLE IF EXISTS public."TestCsvPipeSeparated";
DROP TABLE IF EXISTS public."TestCsvUnquoted";
DROP TABLE IF EXISTS public."TestCsvUtf8";

DROP SCHEMA IF EXISTS "TestSchema" CASCADE;

