FROM mcr.microsoft.com/dotnet/core/sdk:3.0

#copy local files into app

#clone repo
#build repo
#copy output dll into app folder
#show contents of app folder

FROM microsoft/mssql-server-linux:latest

ENV SA_PASSWORD=P@ssw0rd!
ENV ACCEPT_EULA=Y
ENV MSSQL_PID=Express

EXPOSE 1433